### ISSUE TITLE
NP Atlas compound linking has changed

### ISSUE THREAD

**Issue by jvansan** [mwang87/GNPS_ExternalStructureProxy#17]
Hey Ming,

As per my email, we have changed from hash routing to query parameters for the NP Atlas. As such, a small change to the external proxy redirect needs to be made. I'll issue a PR with the necessary change.

**Comment by jvansan** [comment]
I'm actually not going to make a PR, because it's just one character that needs to be changed:

https://github.com/mwang87/GNPS_ExternalStructureProxy/blob/master/views.py#L44

Change the from `https://www.npatlas.org/joomla/index.php/explore/compounds#npaid=%s` -> `https://www.npatlas.org/joomla/index.php/explore/compounds?npaid=%s`

**Comment by mwang87** [comment]
Thanks Jeff! Sounds great. Hope you are doing well in Vancouver

**Comment by mwang87** [comment]
Fixed! Closing.
